#ifndef PAYLOAD_GLSL
#define PAYLOAD_GLSL

struct HitPayload
{
    vec3 HitColor;
    float Distance;
};

#ifdef HITPAYLOAD_OUT
/// @brief HitPayload that contains return information from rays generated by the current shader
layout(location = 0) rayPayloadEXT HitPayload ChildPayload;
#endif // HITPAYLOAD_OUT
#ifdef HITPAYLOAD_IN
/// @brief HitPayload returned to the ray generation context of the current hit/miss shader
layout(location = 1) rayPayloadInEXT HitPayload ReturnPayload;
#endif // HITPAYLOAD_IN

#endif // PAYLOAD_GLSL