#ifndef PAYLOAD_GLSL
#define PAYLOAD_GLSL

// @brief Raytracing Hit payload. This struct is passed as input variable and return variable to hit / miss shaders.
// It is initialized in the shader calling traceRayEXT and returned back to that call after the hit / miss shader 
// and subsequent calls have been resolved
struct HitPayload
{
    vec3 HitColor; // Simple color information
};

#ifdef HITPAYLOAD_OUT
/// @brief HitPayload that contains return information from rays generated by the current shader
layout(location = 0) rayPayloadEXT HitPayload ChildPayload;
#endif // HITPAYLOAD_OUT
#ifdef HITPAYLOAD_IN
/// @brief HitPayload returned to the ray generation context of the current hit/miss shader
layout(location = 1) rayPayloadInEXT HitPayload ReturnPayload;
#endif // HITPAYLOAD_IN

#endif // PAYLOAD_GLSL